### ISSUE TITLE
Not compatible with Django 4.0

### ISSUE THREAD

**Issue by grmoon** [jazzband/django-invitations#182]
Following the installation instructions at https://django-invitations.readthedocs.io/en/latest/installation.html using Django 4.0, the migration step fails with the following error:

 <details>
 <summary>Stack Trace</summary>
 <p>

```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/path/to/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/path/to/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/path/to/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/path/to/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/path/to/lib/python3.8/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/path/to/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/path/to/lib/python3.8/site-packages/invitations/models.py", line 12, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/path/to/lib/python3.8/site-packages/django/utils/translation/__init__.py)
```
</p>
</details>

This issue appears to have been fixed in https://github.com/jazzband/django-invitations/commit/618fc4ef87b9912777255590f289df3ae24ec9f3, it just needs to be released.

**Comment by cloudcode-hungary** [comment]
Is there an ETA for the next PYPI build? We are migrating to 4.0 as of now, and failing at importing signals because of providing_args parameters. I can see that it's already fixed in the code base with https://github.com/jazzband/django-invitations/commit/83e900008afa3c060bed2c5bbf41023cc4268320

**Comment by valberg** [comment]
We are waiting for https://github.com/jazzband/django-invitations/issues/172 to be completed so we can do a "proper" release through jazzband. Hopefully it will happen sooner than later :)

**Comment by Natureshadow** [comment]
It does not seem like this will happen sooner.

This is the only dependency blocking AlekSIS' migration to Django 4.0, and forced us to push an LTS release out depending on Django 3, which will be EOL before AlekSIS 2022.6 will be EOL…

Please help us to not have to push the next release out with an unsupported Django version! If the release is blocked "only" by a CI issue, pelase do the release without the CI.

**Comment by lausek** [comment]
@Natureshadow using a git dependency is not an option?

```bash
pip install git+https://github.com/jazzband/django-invitations.git@dfc65d3e0c27fe6e6d66083621348c149c47a725
```

**Comment by Natureshadow** [comment]
> @Natureshadow using a git dependency is not an option?

Nope.

**Comment by valberg** [comment]
django-invitations 2.0.0 is compatible with django 4.0+
