### ISSUE TITLE
Unable to use with Django v4.1, contains outdated method

### ISSUE THREAD

**Issue by khaw235** [jazzband/django-invitations#191]
Hi,

I tried to use this library. After installation and inserting required details settings.py, when I ran command `python manage.py runserver`. It gave an error that NameError: 'ugettext_lazy' is not defined.

Upon doing some research, I found that ugettext_lazy() method has been deprecated in Django 1.9. Is there any workaround to use the library as I do not plan to reduce my Django version?

**Comment by malmiteria** [comment]
Hi, having the exact same issue here

Here's a traceback if it helps:
```
Using python3.10 (3.10.7)
Traceback (most recent call last):
  File "<redacted>/manage.py", line 22, in <module>
    main()
  File "<redacted>/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "<redacted>/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "<redacted>/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "<redacted>/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "<redacted>/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "<redacted>/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<redacted>/site-packages/invitations/models.py", line 12, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (<redacted>/site-packages/django/utils/translation/__init__.py)
```

**Comment by valberg** [comment]
Hi! A new version supporting Django 4.0+ is coming soon.

**Comment by valberg** [comment]
django-invitations 2.0.0 is compatible with django 4.0+
