### ISSUE TITLE
Migrations Fail When Deploying to AWS with NodeNotFoundError

### ISSUE THREAD

**Issue by infiniteNIL** [jazzband/django-invitations#205]
Everything works fine locally, but when I attempt to deploy to AWS Elastic Beanstalk, migrations fail. The following is from the log:

2022-11-13 23:43:33,659 P31312 [INFO] Command 01_makemigrations
2022-11-13 23:43:34,219 P31312 [INFO] -----------------------Command Output-----------------------
2022-11-13 23:43:34,220 P31312 [INFO] 	Traceback (most recent call last):
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "manage.py", line 22, in <module>
2022-11-13 23:43:34,220 P31312 [INFO] 	    main()
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "manage.py", line 18, in main
2022-11-13 23:43:34,220 P31312 [INFO] 	    execute_from_command_line(sys.argv)
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
2022-11-13 23:43:34,220 P31312 [INFO] 	    utility.execute()
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
2022-11-13 23:43:34,220 P31312 [INFO] 	    self.fetch_command(subcommand).run_from_argv(self.argv)
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
2022-11-13 23:43:34,220 P31312 [INFO] 	    self.execute(*args, **cmd_options)
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
2022-11-13 23:43:34,220 P31312 [INFO] 	    output = self.handle(*args, **options)
2022-11-13 23:43:34,220 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
2022-11-13 23:43:34,221 P31312 [INFO] 	    res = handle_func(*args, **kwargs)
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 100, in handle
2022-11-13 23:43:34,221 P31312 [INFO] 	    loader = MigrationLoader(None, ignore_no_migrations=True)
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/db/migrations/loader.py", line 58, in __init__
2022-11-13 23:43:34,221 P31312 [INFO] 	    self.build_graph()
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/db/migrations/loader.py", line 276, in build_graph
2022-11-13 23:43:34,221 P31312 [INFO] 	    self.graph.validate_consistency()
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/db/migrations/graph.py", line 198, in validate_consistency
2022-11-13 23:43:34,221 P31312 [INFO] 	    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/db/migrations/graph.py", line 198, in <listcomp>
2022-11-13 23:43:34,221 P31312 [INFO] 	    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
2022-11-13 23:43:34,221 P31312 [INFO] 	  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/db/migrations/graph.py", line 60, in raise_error
2022-11-13 23:43:34,221 P31312 [INFO] 	    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
2022-11-13 23:43:34,221 P31312 [INFO] 	django.db.migrations.exceptions.NodeNotFoundError: Migration webapp.0032_invitationdetails_installer_invitation_and_more dependencies reference nonexistent parent node ('invitations', '0004_alter_invitation_id')

It just seems like it can't find the migrations for invitations. I have verified that they are in the venv/lib/site-packages/invitations/migrations. 

Am I missing a setting or command argument or something or is this a bug in Django or Invitations? Any workarounds?

Thanks. I'm pretty new to Django.

**Comment by kalzun** [comment]
Yes, due to a change in Django in 3.2 [(release notes for 3.2)](https://docs.djangoproject.com/en/4.1/releases/3.2/#customizing-type-of-auto-created-primary-keys), and the settings in the default settings file is now setting it as `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'`, the package will make a migration of this when you run `python manage.py makemigrations` locally.

I have made a pull request #206 to the project, maybe that can help you.

**Comment by mitch-PV01** [comment]
This is still an issue, running `makemigrations` locally when using `BigAutoField` will generate `invitations/migrations/0004_alter_invitation_id.py` inside `site_packages`. Can this migration be committed to the repo?

**Comment by KrYpTeD974** [comment]
@valberg, Could you please release a new version with this fix ? The 2.0.0 is not usable in production in the current state.

**Comment by valberg** [comment]
Hi! I have just issued 2.1.0 release. I hope this fixes your problem. Sorry for the delay.
